# Generated by Django 5.2.13 on 2026-05-23

from django.conf import settings
from django.contrib.auth.hashers import make_password
import django.db.models.deletion
from django.db import migrations, models


SECURITY_QUESTION = "What is your dream place ?"
DEFAULT_SECURITY_ANSWER = "kathmandu"


def create_default_security_answers(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserSecurityAnswer = apps.get_model("expenses", "UserSecurityAnswer")
    for user in User.objects.all():
        UserSecurityAnswer.objects.get_or_create(
            user=user,
            defaults={
                "question": SECURITY_QUESTION,
                "answer_hash": make_password(DEFAULT_SECURITY_ANSWER),
            },
        )


def remove_default_security_answers(apps, schema_editor):
    UserSecurityAnswer = apps.get_model("expenses", "UserSecurityAnswer")
    UserSecurityAnswer.objects.filter(question=SECURITY_QUESTION).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_familybudget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSecurityAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(default=SECURITY_QUESTION, max_length=150)),
                ("answer_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_answer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.RunPython(create_default_security_answers, remove_default_security_answers),
    ]
