# Generated by Django 6.0.7 on 2026-07-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alertlog_recurringexpense_usersettings'),
        ('expenses', '0004_recurringexpense'),
    ]

    operations = [
    ]
