# Generated by Django 6.0.7 on 2026-07-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_merge_20260726_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringexpense',
            options={'ordering': ['next_due_date', 'title']},
        ),
    ]
